janus-idp/janus-idp.github.io

apps/landing-page/pages/blog/initial-plugins.mdx

fix: Add title to the blogpost

---

apps/landing-page/theme.config.tsx
packages/ui/components/footer/footer.tsx

- Fix the invite links to be able to join the Slack Janus Community
- Rename the Discord label to Slack
- Open the footer links to a new tab
Fixes #4

Fix the invite links to Slack

---

apps/landing-page/pages/blog/getting-started-with-the-backstage-helm-chart-part-1.mdx

Added port to port-forward command

Added port to port-forward command

---

apps/landing-page/pages/community.mdx

The community mailing list and calendar were a little hard to find, so I added them to the community page.
n/a
- ~~Unit Tests~~
- ~~E2E Tests~~
I checked all these links locally via `pnpm run dev` as well as `pnpm run lint`; hopefully no failures on those is enough.

Add links to community resources

---

apps/landing-page/pages/blog/_meta.json

Disable new blog from 2/17 til precursor is published

disable new blog til precursor is added

---

apps/landing-page/pages/blog/_meta.json
apps/landing-page/pages/blog/deploying-backstage-onto-openshift-using-helm.mdx

new blog from Andrew: deploying backstage onto openshift using helm

new blog: deploying backstage onto openshift using helm

---

apps/landing-page/pages/blog/exploring-quay-registry-in-backstage.mdx

fix: Quay blog typo in imported package name

---

apps/landing-page/pages/blog/janus-backstage-images-available-on-quay.mdx

fix title of latest blog which had erroneous title

fix title of latest blog

---

apps/landing-page/pages/community.mdx

update with an un-expiring slack invite
Fixes #40

update with un-expiring slack invite

---

.github/workflows/ci.yaml
.github/workflows/deploy-landing-page.yaml
apps/landing-page/.gitignore
apps/landing-page/pages/rss.tsx
apps/landing-page/theme.config.tsx
package.json
packages/landing-page-tests/package.json
packages/landing-page-tests/tests/broken-links.test.ts
packages/ui/package.json
packages/ui/utils/generate-rss-feed/generate-rss-feed.ts
packages/ui/utils/generate-rss-feed/index.ts
pnpm-lock.yaml
turbo.json

Adds RSS feed
Fixes https://github.com/janus-idp/janus-idp.github.io/issues/28

Add RSS feed

---

.github/workflows/deploy-website.yaml

Fix gh actions

---

apps/website/content/plugin-list.ts
apps/website/docusaurus.config.js
apps/website/src/pages/index.tsx
apps/website/src/pages/plugins.tsx

Update 3scale details

---

README.md

Update the instructions how to use the new website and to update it
Fixes #?

Update the instructions how to use the new website and to update it

---

.github/workflows/deploy-website.yaml
apps/website/docusaurus.config.js
apps/website/package.json
pnpm-lock.yaml
turbo.json

Add Google Analytics to the website
Fixes #?

Add Google Analytics

---

packages/ui/providers/analytics-provider/analytics-provider.tsx

Fix analytics

---

.github/workflows/deploy-website.yaml
README.md

Adds repository dispatch to the deploy website action
related: https://github.com/janus-idp/backstage-plugins/pull/374
Fixes #?

Add repository dispatch to deploy website action

---

README.md

Add more info about how to update the plugins

---

packages/ui/components/plugin-grid/plugin-grid.tsx

Make the main plugin page responsive

---

apps/website/content/plugin-list.js

fix(website): fix plugin href

---

.github/workflows/ci.yaml
.github/workflows/deploy-website.yaml
pnpm-lock.yaml

chore(gh-actions): update pnpm version and remove e2e section

---

.github/renovate.json

Adds renovate bot config
Fixes #?

chore(monorepo): add renovate bot config

---

.github/renovate.json

fix(renovate): update renovate config

---

apps/website/src/theme/Root.tsx

Fixes https://github.com/janus-idp/janus-idp.github.io/issues/132

chore(website): remove banner

---

.husky/scripts/sync-node-modules

Fixes https://github.com/janus-idp/janus-idp.github.io/issues/135

fix(husky): update git install hooks

---

apps/website/src/lib/providers/environment-provider.tsx
packages/ui/contexts/environment-context/environment-context.tsx

Fixes https://github.com/janus-idp/janus-idp.github.io/issues/138

fix(ui): update environment context typing

---

apps/website/content/gpts-list.js
apps/website/content/plugin-list.js
apps/website/src/lib/utils/fetch-remote-content.js
packages/ui/package.json
packages/ui/types/index.ts
pnpm-lock.yaml

Update remote content [regex](https://github.com/janus-idp/janus-idp.github.io/blob/main/apps/website/src/lib/utils/fetch-remote-content.js#L17) to include relative non image files. The website cannot build without this fix.
Fixes https://github.com/janus-idp/janus-idp.github.io/issues/188

fix(website): update remote content regex to include relative non image files

---

apps/website/content/gpts-list.js

Fixes build issue after https://github.com/janus-idp/software-templates/pull/164

fix: update paths to GPTs to fix the build

---

apps/website/content/gpts-list.js

chore(website): update dotnet GPT location

---

apps/website/content/plugin-list.js

fix(website): jfrog title description

---

package.json
turbo.json

fix(scripts): fix lint-staged

---

apps/website/content/plugin-list.js

Updates ACR plugin page to provide correct documentation
Fixes #236

chore: update documentation link for ACR page

---

apps/website/blog/2023-11-03-the-digital-experience-platform-journey-with-red-hat-developer-hub-part-1/index.mdx
apps/website/blog/authors.yml

Added Adoption Status Blog for the DXP Teams

---

.github/workflows/deploy-website.yaml

chore(deps): update cd workflow actions

---

apps/website/src/pages/community/index.mdx

Fix typo and add a link to the code of conduct
n/a

Add code of conduct link

---

.github/workflows/deploy-website.yaml

fix(cd): update permissions

---

apps/website/docs/intro.mdx
apps/website/docusaurus.config.ts

This PR removes the WIP docs section as it is not expected to be progressed.
Fixes https://issues.redhat.com/browse/RHIDP-2708

removed WIP docs

---

OWNERS

chore: add bethgriggs to owners

---

apps/website/blog/2022-12-21-newly-released-backstage-plugins/index.mdx
apps/website/blog/2023-01-15-getting-started-with-the-backstage-helm-chart/index.mdx
apps/website/blog/2023-01-17-enabling-keycloak-authentication-in-backstage/index.mdx
apps/website/blog/2023-01-25-exploring-the-flexibility-of-the-backstage-helm-chart/index.mdx
apps/website/blog/2023-02-06-ingesting-keycloak-org-data-into-the-backstage-catalog/index.mdx
apps/website/blog/2023-02-17-deploying-backstage-onto-openshift-using-helm/index.mdx
apps/website/blog/2023-02-20-exploring-quay-registry-in-backstage/index.mdx
apps/website/blog/2023-02-20-using-openshift-authentication-to-secure-access-to-backstage/index.mdx
apps/website/blog/2023-02-28-exposing-your-3scale-apis/index.mdx
apps/website/blog/2023-03-01-janus-backstage-images-on-quay/index.mdx
apps/website/blog/2023-03-06-topology/index.mdx
apps/website/blog/2023-06-03-production-ready-techdocs/index.mdx
apps/website/blog/2023-06-23-topology-plugin-overview/index.mdx
apps/website/blog/2023-08-23-creating-your-first-backstage-backend-plugin/index.mdx
apps/website/blog/2023-10-11-frontend-plugin/index.mdx
apps/website/blog/2023-11-03-the-digital-experience-platform-journey-with-red-hat-developer-hub-part-1/index.mdx
packages/ui/components/banner/archive-banner.tsx

This PR adds a banner to all blog posts indicating the content is archived  in order to avoid users from attempting to use legacy content and tutorials 
Fixes https://issues.redhat.com/browse/RHIDP-2896

added archive banner for all blog posts

---

OWNERS

chore: add 04kash to owners

---

apps/website/blog/2024-07-05-future-of-janus-community/index.mdx
apps/website/blog/authors.yml

blog: add Future of Janus Community post 2024-07-05
